// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Config {
  apiKey: string;
  model: string;
}

export function GetConfig(): Promise<Config>;
export function GetNotes(): Promise<string>;
export function SaveConfig(arg1: string, arg2: string): Promise<void>;
export function SaveNotes(arg1: string): Promise<void>;
export function SendMessage(arg1: string): Promise<string>;
